# Data Cleaning & Structural Validation

**Dataset:** `Raw_clean_dataset.csv`

**Objective:** Clean and validate the provided customer churn dataset by checking missing values, duplicate records, data types, inconsistent values, invalid values, and possible outliers.

**Submission outputs:**
- Cleaned dataset: `cleaned_customer_churn.csv`
- This Jupyter Notebook

## Step 1 — Import Libraries

Pandas is used for data manipulation and NumPy is used for numerical operations.

In [17]:
import pandas as pd
import numpy as np

## Step 2 — Load the Actual Raw Dataset

The provided file is `Raw_clean_dataset.csv`. The raw dataset is loaded without changing the original CSV file.

In [18]:
input_file = "Raw_clean_dataset.csv"

df = pd.read_csv(input_file)

print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Dataset loaded successfully.
Rows: 600
Columns: 13

,CustomerID,Age,Region,TenureMonths,SubscriptionType,MonthlyChargesINR,TotalChargesINR,ContractType,SupportTickets,LatePayments,PaymentMethod,AutoPay,Churn
0,CUST-100001,20,North,9,Pro,13097.76,unknown,Month-to-Month,1,2,Card,No,Yes
1,CUST-100002,55,Central,52,Pro,1101.18,57334.22,One Year,0,0,Card,Yes,No
2,CUST-100003,40,Central,67,Standard,692.66,44554.47,Month-to-Month,6,2,UPI,No,Yes
3,CUST-100004,53,South,48,Pro,1156.49,53956.12,One Year,2,2,Card,Yes,No
4,CUST-100005,21,West,24,Standard,754.16,18191.59,Month-to-Month,0,1,Card,Yes,No

## Step 3 — Inspect the Dataset

The actual raw dataset contains **600 rows and 13 columns**.

The columns are:
`CustomerID, Age, Region, TenureMonths, SubscriptionType, MonthlyChargesINR, TotalChargesINR, ContractType, SupportTickets, LatePayments, PaymentMethod, AutoPay, Churn`.

In [3]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

Dataset shape: (600, 13)

Column names:
['CustomerID', 'Age', 'Region', 'TenureMonths', 'SubscriptionType', 'MonthlyChargesINR', 'TotalChargesINR', 'ContractType', 'SupportTickets', 'LatePayments', 'PaymentMethod', 'AutoPay', 'Churn']

Data types:
CustomerID               str
Age                    int64
Region                   str
TenureMonths           int64
SubscriptionType         str
MonthlyChargesINR    float64
TotalChargesINR          str
ContractType             str
SupportTickets         int64
LatePayments           int64
PaymentMethod            str
AutoPay                  str
Churn                    str
dtype: object

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         600 non-null    str
 1   Age                600 non-null    int64
 2   Region             588 non-null    str
 3   TenureMonths       600 non-null    int64
 4   SubscriptionType   600 non-null    str
 5   MonthlyChargesINR  600 non-null    float64
 6   TotalChargesINR    600 non-null    str
 7   ContractType       600 non-null    str
 8   SupportTickets     600 non-null    int64
 9   LatePayments       600 non-null    int64
 10  PaymentMethod      600 non-null    str
 11  AutoPay            600 non-null    str
 12  Churn              600 non-null    str
dtypes: float64(1), int64(4), str(8)
memory usage: 61.1 KB

In [4]:
print("Statistical summary:")
display(df.describe(include="all"))

Statistical summary:

,CustomerID,Age,Region,TenureMonths,SubscriptionType,MonthlyChargesINR,TotalChargesINR,ContractType,SupportTickets,LatePayments,PaymentMethod,AutoPay,Churn
count,600,600.000000,588,600.000000,600,600.000000,600,600,600.000000,600.000000,600,600,600
unique,600,NaN,5,NaN,3,NaN,588,3,NaN,NaN,4,2,2
top,CUST-100001,NaN,Central,NaN,Basic,NaN,unknown,Month-to-Month,NaN,NaN,Wallet,Yes,No
freq,1,NaN,125,NaN,211,NaN,10,316,NaN,NaN,161,350,353
mean,NaN,42.520000,NaN,35.541667,NaN,869.032833,NaN,NaN,1.760000,1.275000,NaN,NaN,NaN
std,NaN,14.807488,NaN,20.848406,NaN,1109.118011,NaN,NaN,1.426812,1.068306,NaN,NaN,NaN
min,NaN,18.000000,NaN,0.000000,NaN,364.340000,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,NaN,30.000000,NaN,18.000000,NaN,451.557500,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN
50%,NaN,42.000000,NaN,34.000000,NaN,726.105000,NaN,NaN,2.000000,1.000000,NaN,NaN,NaN
75%,NaN,55.000000,NaN,54.000000,NaN,1103.502500,NaN,NaN,3.000000,2.000000,NaN,NaN,NaN
max,NaN,68.000000,NaN,72.000000,NaN,13858.560000,NaN,NaN,6.000000,4.000000,NaN,NaN,NaN

## Step 4 — Check Missing Values

Missing values are counted for every column. This helps identify fields that need cleaning or imputation.

In [5]:
missing_before = df.isnull().sum()

print("Missing values by column:")
print(missing_before)

print("\nTotal missing values:", missing_before.sum())

Missing values by column:
CustomerID            0
Age                   0
Region               12
TenureMonths          0
SubscriptionType      0
MonthlyChargesINR     0
TotalChargesINR       0
ContractType          0
SupportTickets        0
LatePayments          0
PaymentMethod         0
AutoPay               0
Churn                 0
dtype: int64

Total missing values: 12

### Observation from the raw dataset

The raw dataset contains **12 missing values in `Region`**. Other columns do not contain standard CSV null values.

These missing `Region` values will be replaced with the category **`Unknown`** so that customer records are not unnecessarily deleted.

## Step 5 — Check Duplicate Records

Duplicate rows are identified before removing them.

In [19]:
duplicate_count = df.duplicated().sum()

print("Duplicate records:", duplicate_count)

if duplicate_count > 0:
    display(df[df.duplicated(keep=False)])
else:
    print("No duplicate records found.")

Duplicate records: 0
No duplicate records found.

### Observation

The raw dataset contains **0 duplicate rows**, so no duplicate records need to be removed at this stage.

## Step 6 — Standardize Column Headers

Column headers are converted to lowercase and spaces/special separators are standardized to underscores.

In [7]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

print("Standardized column names:")
print(df.columns.tolist())

Standardized column names:
['customerid', 'age', 'region', 'tenuremonths', 'subscriptiontype', 'monthlychargesinr', 'totalchargesinr', 'contracttype', 'supporttickets', 'latepayments', 'paymentmethod', 'autopay', 'churn']

## Step 7 — Clean Text and Categorical Values

Leading and trailing spaces are removed from text fields. Categorical values are standardized for consistency.

In [8]:
text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    df[column] = df[column].str.strip()

categorical_columns = [
    "region",
    "subscriptiontype",
    "contracttype",
    "paymentmethod",
    "autopay",
    "churn"
]

for column in categorical_columns:
    if column in df.columns:
        df[column] = df[column].str.title()

print("Text and categorical values standardized.")

Text and categorical values standardized.

C:\Users\USER\AppData\Local\Temp\ipykernel_2780\109628205.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

## Step 8 — Handle Missing and `unknown` Values

`Region` has missing values, so they are replaced with `Unknown`.

`TotalChargesINR` contains the text value `unknown`. It is treated as a missing numerical value, converted to `NaN`, and then filled using the median of the valid `TotalChargesINR` values. This preserves the customer records while making the column numeric.

In [9]:
# Standardize missing Region values
if "region" in df.columns:
    df["region"] = df["region"].fillna("Unknown")

# Convert the 'unknown' text in total charges to a missing value
if "totalchargesinr" in df.columns:
    df["totalchargesinr"] = (
        df["totalchargesinr"]
        .replace(r"(?i)^unknown$", np.nan, regex=True)
    )

print("Missing Region values after treatment:",
      df["region"].isna().sum() if "region" in df.columns else "N/A")

print("Missing Total Charges after converting 'unknown':",
      df["totalchargesinr"].isna().sum() if "totalchargesinr" in df.columns else "N/A")

Missing Region values after treatment: 0
Missing Total Charges after converting 'unknown': 10

### Observation

The raw dataset contains **10 `unknown` values in `TotalChargesINR`**.

These are treated as missing numerical values rather than as a valid category.

## Step 9 — Validate and Convert Data Types

Expected numerical columns are converted to numeric data types. Invalid text entries become `NaN`, which can then be identified.

In [10]:
numeric_columns = [
    "age",
    "tenuremonths",
    "monthlychargesinr",
    "totalchargesinr",
    "supporttickets",
    "latepayments"
]

for column in numeric_columns:
    if column in df.columns:
        df[column] = pd.to_numeric(df[column], errors="coerce")

print("Data types after conversion:")
print(df.dtypes)

Data types after conversion:
customerid               str
age                    int64
region                   str
tenuremonths           int64
subscriptiontype         str
monthlychargesinr    float64
totalchargesinr      float64
contracttype             str
supporttickets         int64
latepayments           int64
paymentmethod            str
autopay                  str
churn                    str
dtype: object

## Step 10 — Handle Remaining Missing Numerical Values

For numerical columns, any remaining missing values are replaced with the median of that column. Median imputation is used because it is less affected by extreme values than the mean.

In [11]:
for column in numeric_columns:
    if column in df.columns and df[column].isna().sum() > 0:
        median_value = df[column].median()
        df[column] = df[column].fillna(median_value)
        print(f"{column}: missing values replaced with median = {median_value}")

print("\nMissing values after treatment:")
print(df.isnull().sum())

totalchargesinr: missing values replaced with median = 22426.625

Missing values after treatment:
customerid           0
age                  0
region               0
tenuremonths         0
subscriptiontype     0
monthlychargesinr    0
totalchargesinr      0
contracttype         0
supporttickets       0
latepayments         0
paymentmethod        0
autopay              0
churn                0
dtype: int64

## Step 11 — Check Invalid Values

The following logical checks are performed:
- Age should be between 0 and 100.
- Tenure should not be negative.
- Charges should not be negative.
- Support tickets and late payments should not be negative.

In [12]:
invalid_checks = {}

if "age" in df.columns:
    invalid_checks["Invalid age"] = ((df["age"] < 0) | (df["age"] > 100)).sum()

if "tenuremonths" in df.columns:
    invalid_checks["Invalid tenure"] = (df["tenuremonths"] < 0).sum()

if "monthlychargesinr" in df.columns:
    invalid_checks["Invalid monthly charges"] = (df["monthlychargesinr"] < 0).sum()

if "totalchargesinr" in df.columns:
    invalid_checks["Invalid total charges"] = (df["totalchargesinr"] < 0).sum()

if "supporttickets" in df.columns:
    invalid_checks["Invalid support tickets"] = (df["supporttickets"] < 0).sum()

if "latepayments" in df.columns:
    invalid_checks["Invalid late payments"] = (df["latepayments"] < 0).sum()

for check, count in invalid_checks.items():
    print(f"{check}: {int(count)}")

Invalid age: 0
Invalid tenure: 0
Invalid monthly charges: 0
Invalid total charges: 0
Invalid support tickets: 0
Invalid late payments: 0

## Step 12 — Detect Possible Outliers Using IQR

The Interquartile Range (IQR) method is used to flag possible outliers.

**Important:** Possible outliers are not automatically deleted. An unusual value can still be a valid customer record, so the values are only flagged for review.

In [13]:
outlier_columns = [
    "age",
    "tenuremonths",
    "monthlychargesinr",
    "totalchargesinr",
    "supporttickets",
    "latepayments"
]

outlier_results = []

for column in outlier_columns:
    if column in df.columns:
        q1 = df[column].quantile(0.25)
        q3 = df[column].quantile(0.75)
        iqr = q3 - q1

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        mask = (df[column] < lower_bound) | (df[column] > upper_bound)

        outlier_results.append({
            "Column": column,
            "Q1": q1,
            "Q3": q3,
            "Lower Bound": lower_bound,
            "Upper Bound": upper_bound,
            "Possible Outliers": int(mask.sum())
        })

outlier_table = pd.DataFrame(outlier_results)
display(outlier_table)

,Column,Q1,Q3,Lower Bound,Upper Bound,Possible Outliers
0,age,30.0000,55.0000,-7.50000,92.50000,0
1,tenuremonths,18.0000,54.0000,-36.00000,108.00000,0
2,monthlychargesinr,451.5575,1103.5025,-526.36000,2081.42000,7
3,totalchargesinr,11149.3750,37168.8375,-27879.81875,76198.03125,11
4,supporttickets,1.0000,3.0000,-2.00000,6.00000,0
5,latepayments,0.0000,2.0000,-3.00000,5.00000,0

## Step 13 — Remove Duplicate Rows

Duplicate rows are removed as a final structural-cleaning step. The raw dataset has already been checked for duplicates.

In [14]:
rows_before = len(df)

df = df.drop_duplicates().copy()

rows_after = len(df)

print("Rows before duplicate removal:", rows_before)
print("Rows after duplicate removal:", rows_after)
print("Duplicates removed:", rows_before - rows_after)

Rows before duplicate removal: 600
Rows after duplicate removal: 600
Duplicates removed: 0

## Step 14 — Final Validation

The cleaned dataset is checked again for shape, missing values, duplicates, data types, and a sample of the cleaned records.

In [15]:
print("FINAL DATASET SHAPE")
print("-------------------")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nFINAL MISSING VALUES")
print("--------------------")
print(df.isnull().sum())

print("\nFINAL DUPLICATE COUNT")
print("---------------------")
print(df.duplicated().sum())

print("\nFINAL DATA TYPES")
print("-----------------")
print(df.dtypes)

print("\nFIRST 5 CLEANED RECORDS")
print("-----------------------")
display(df.head())

FINAL DATASET SHAPE
-------------------
Rows: 600
Columns: 13

FINAL MISSING VALUES
--------------------
customerid           0
age                  0
region               0
tenuremonths         0
subscriptiontype     0
monthlychargesinr    0
totalchargesinr      0
contracttype         0
supporttickets       0
latepayments         0
paymentmethod        0
autopay              0
churn                0
dtype: int64

FINAL DUPLICATE COUNT
---------------------
0

FINAL DATA TYPES
-----------------
customerid               str
age                    int64
region                   str
tenuremonths           int64
subscriptiontype         str
monthlychargesinr    float64
totalchargesinr      float64
contracttype             str
supporttickets         int64
latepayments           int64
paymentmethod            str
autopay                  str
churn                    str
dtype: object

FIRST 5 CLEANED RECORDS
-----------------------

,customerid,age,region,tenuremonths,subscriptiontype,monthlychargesinr,totalchargesinr,contracttype,supporttickets,latepayments,paymentmethod,autopay,churn
0,CUST-100001,20,North,9,Pro,13097.76,22426.625,Month-To-Month,1,2,Card,No,Yes
1,CUST-100002,55,Central,52,Pro,1101.18,57334.220,One Year,0,0,Card,Yes,No
2,CUST-100003,40,Central,67,Standard,692.66,44554.470,Month-To-Month,6,2,Upi,No,Yes
3,CUST-100004,53,South,48,Pro,1156.49,53956.120,One Year,2,2,Card,Yes,No
4,CUST-100005,21,West,24,Standard,754.16,18191.590,Month-To-Month,0,1,Card,Yes,No

## Step 15 — Cleaning Decisions Record

| Issue | Cleaning decision | Reason |
|---|---|---|
| Missing `Region` | Replaced with `Unknown` | Keeps the customer record while clearly indicating unavailable region information |
| `unknown` in `TotalChargesINR` | Converted to missing and filled with median | Makes the field numeric and suitable for analysis |
| Duplicate rows | Checked and removed if present | Prevents repeated records |
| Column headers | Standardized | Consistent naming convention |
| Text values | Stripped and standardized | Improves categorical consistency |
| Numeric fields | Converted to numeric types | Structural validation |
| Invalid numeric values | Checked | Prevents logically impossible values |
| Possible outliers | Detected using IQR and retained | Outliers may be genuine observations, so they are not automatically deleted |

## Step 16 — Export the Cleaned Dataset

The final cleaned data is exported as `cleaned_customer_churn.csv`.

In [16]:
output_file = "cleaned_customer_churn.csv"

df.to_csv(output_file, index=False)

print(f"Cleaned dataset saved as: {output_file}")

Cleaned dataset saved as: cleaned_customer_churn.csv

## Step 17 — Final Submission Checklist

The required submission should contain:

1. **`cleaned_customer_churn.csv`** — cleaned dataset
2. **`Data_Cleaning_Structural_Validation.ipynb`** — completed Jupyter Notebook

Supporting files:
- `Raw_clean_dataset.csv` — original raw dataset
- `data_cleaning.py` — Python cleaning script

**Before submission:** run all notebook cells successfully and save the notebook with **Ctrl + S**.